// Fichas de consulta para o mestre, redigidas a partir do PDF fornecido.
// Relações são declaradas somente quando o livro as estabelece.
// "tarokka" registra quando o livro permite que a pessoa seja o aliado sorteado por Madame Eva.
const people = [
  // ——— Os von Zarovich e o centro da maldição
  {id:'strahd',name:'Strahd von Zarovich',aliases:['Vasili von Holtz'],place:'Castelo Ravenloft',role:'Conde de Baróvia · vampiro',kind:'Antagonista',
    summary:'Senhor de Ravenloft e centro da maldição de Baróvia. Soldado, conquistador e mago, matou o irmão Sergei para selar um pacto com os Poderes das Trevas e se tornou vampiro.',
    detail:'Acredita que Ireena é a reencarnação de Tatyana e pretende transformá-la em consorte na próxima visita; já bebeu seu sangue duas vezes. Também quer capturar Rudolph van Richten e quebrar seu espírito nas masmorras. Quando estrangeiros chegam, testa-os à procura de um sucessor ou de uma nova distração, mas sua arrogância o impede de reconhecer alguém à sua altura. Não sente remorso: diz que a alma de Tatyana lhe pertence. Sob o disfarce de Vasili von Holtz, corrompeu o Abade de Krezk e comprou a colaboração de Henrik van der Voort em Vallaki. Se o Memorial de Strahd cair nas mãos do grupo, recuperá-lo passa a ser sua prioridade.'},
  {id:'ireena',name:'Ireena Kolyana',place:'Vila de Baróvia',role:'Filha adotiva de Kolyan',kind:'Aliada',
    summary:'Jovem de vontade firme, duas vezes mordida por Strahd. É idêntica a Tatyana, e o conde acredita que ela seja sua reencarnação.',
    detail:'Kolyan a encontrou ainda menina à margem dos Bosques de Svalich, perto do Pilar de Ravenloft, sem nenhuma lembrança do passado. Ela não se recorda com clareza dos encontros com o vampiro. Aceita a ajuda do grupo, mas insiste em sepultar o pai antes de deixar a vila. Não sabe que Izek Strazni, capitão da guarda de Vallaki, é seu irmão biológico. Tem alma, o que a torna presa valiosa para Strahd.',
    tarokka:'Insiste em ir a Ravenloft quando sabe da leitura, contra a vontade de Ismark, mas só depois que Kolyan for enterrado.'},
  {id:'ismark',name:'Ismark Kolyanovich',place:'Vila de Baróvia',role:'Filho do burgomestre',kind:'Aliado',
    summary:'Chamado de Ismark, o Menor. Espera na taverna Sangue da Videira e pede aos aventureiros que protejam a irmã adotiva e a escoltem até Vallaki.',
    detail:'Treinou com armas esperando um dia enfrentar Strahd, mas sabe que sozinho não teria chance. Aceita acompanhar o grupo depois que Ireena estiver segura. Se sobreviver à aventura, pode assumir o cargo de burgomestre da vila.',
    tarokka:'Só acompanha o grupo até Ravenloft depois de saber que Ireena está em segurança.'},
  {id:'kolyan',name:'Kolyan Indirovich',place:'Vila de Baróvia',role:'Burgomestre falecido',kind:'Histórico',
    summary:'Burgomestre da vila, pai de Ismark e pai adotivo de Ireena. Morreu dias antes da chegada do grupo, depois de semanas de ataques à mansão.',
    detail:'Encontrou Ireena ainda criança à margem dos Bosques de Svalich e a criou com amor. Seu corpo aguarda sepultamento na mansão. Escreveu uma carta verdadeira pedindo ajuda, levada por Dalvan Olensky; a outra “carta de Kolyan”, entregue por Arrigal no gancho de abertura, foi escrita por Strahd como isca.'},
  {id:'tatyana',name:'Tatyana',place:'Passado de Ravenloft',role:'Noiva de Sergei',kind:'Histórico',
    summary:'Jovem baroviana de linhagem fina e beleza notável, noiva de Sergei e objeto da obsessão de Strahd. Morreu na noite do casamento.',
    detail:'Rejeitou os presentes e a atenção de Strahd e se apaixonou pelo irmão mais novo. No dia do casamento, depois que Strahd matou Sergei, fugiu pelos jardins e se atirou de uma varanda do castelo. Sua alma renasce em outras mulheres: o livro apresenta Marina e, no presente, Ireena. Um retrato dela, encomendado por Strahd, fica em Ravenloft.'},
  {id:'sergei',name:'Sergei von Zarovich',place:'Passado de Ravenloft',role:'Irmão de Strahd',kind:'Histórico',
    summary:'Irmão mais novo e mais afetuoso de Strahd, noivo de Tatyana. Foi assassinado por Strahd no dia do casamento; seu sangue selou o pacto sombrio.',
    detail:'A mãe, Ravenovia, o manteve longe dos campos de batalha. Sua espada de punho de platina e lâmina de cristal foi desmontada por Khazan a mando de Strahd; o punho sobreviveu e deu origem à Espada Solar. Seu túmulo em Ravenloft é um raro lugar de paz. Em um dos desfechos possíveis, o espírito de Sergei aparece para levar Ireena consigo.'},
  {id:'barov',name:'Rei Barov von Zarovich',place:'Passado de Ravenloft',role:'Pai de Strahd',kind:'Histórico',
    summary:'Rei guerreiro, pai de Strahd e Sergei. O vale de Baróvia foi batizado em sua homenagem depois de sua morte.',
    detail:'Passou a vida em cruzadas. Com a ajuda de Rahadin, subjugou os elfos das sombras e fez do elfo um membro honorário da família. Numa das campanhas, teve uma filha com uma mulher Vistana: Katarina, a futura Madame Eva. Ele e Ravenovia estão sepultados juntos em Ravenloft, local possível do confronto final.'},
  {id:'ravenovia',name:'Rainha Ravenovia van Roeyen',place:'Passado de Ravenloft',role:'Mãe de Strahd',kind:'Histórico',
    summary:'Rainha, mãe de Strahd e Sergei. O Castelo Ravenloft leva o seu nome, mas ela morreu na viagem para conhecê-lo.',
    detail:'Temia a frieza que a guerra criou em Strahd e protegia Sergei. Baniu a parteira Baba Lysaga por causa da obsessão doentia dela pelo bebê Strahd; a bruxa passou a pedir à Mãe Noite a doença e a morte da rainha. Strahd selou o corpo da mãe numa cripta sob o castelo.'},
  {id:'rahadin',name:'Rahadin',place:'Castelo Ravenloft',role:'Mordomo do castelo',kind:'Antagonista',
    summary:'Elfo das sombras que serve a família von Zarovich há quase quinhentos anos. Quem chega perto dele ouve os gritos de todos que ele já matou.',
    detail:'Exilado por se recusar a servir um príncipe que julgava fraco, ajudou o rei Barov a conquistar seu próprio povo e foi adotado como membro honorário da família. Lutou como general de Strahd e depois assumiu a administração de Ravenloft, disciplinando os criados com crueldade. Desconfiou de Patrina desde o início e, após a morte de Tatyana, atraiu outras mulheres ao castelo para distrair o mestre. Quando os elfos apedrejaram Patrina, executou as elfas do clã e cortou as orelhas de Kasimir. Se Strahd for derrotado, tenta vingá-lo.'},
  {id:'baba',name:'Baba Lysaga',place:'Ruínas de Berez',role:'Bruxa do pântano',kind:'Antagonista',
    summary:'Antiga parteira da rainha Ravenovia, devota da Mãe Noite. Acredita ser a verdadeira mãe de Strahd e age nas sombras para protegê-lo.',
    detail:'Pôs em Strahd bebê a “faísca da magia” e cantava junto a seu berço até ser banida pela rainha. Nunca mais viu Strahd e nunca o confrontou, com medo de ser rejeitada. Vive numa cabana rastejante animada por uma gema roubada do Mago dos Vinhos, voa num crânio gigante e se banha em sangue para conter a velhice. Com a ajuda de uma convenção de bruxas de Ravenloft, descobriu os Guardiões da Pena e envia espantalhos para caçar corvos e homens-corvo. Mantém a ilusão de um bebê a quem chama de “Strahd”.'},
  {id:'eva',name:'Madame Eva',aliases:['Katarina'],place:'Acampamento Vistana do Lago Tser',role:'Vidente · leitora de tarokka',kind:'Neutra',
    summary:'Vidente Vistana que lê as cartas tarokka e define, para cada campanha, onde estão os artefatos, quem é o aliado e onde Strahd será enfrentado. É a meia-irmã secreta do conde.',
    detail:'Seu nome verdadeiro é Katarina, filha do rei Barov com uma mulher Vistana. Mais de quatrocentos anos atrás trabalhou como criada em Ravenloft e presenciou o casamento de Sergei e Tatyana. Depois da tragédia, fez um pacto com a Mãe Noite: trocou a juventude pelo poder da clarividência, para desfazer o mal causado pelo irmão. Deseja ver Strahd livre da maldição, destruído ou substituído, e trata os aventureiros como meios para isso. Os Poderes Sombrios a consideram digna de ser a nova senhora de Baróvia, mas ela recusa. Nenhum Vistana conhece sua verdadeira identidade.'},

  // ——— Vistani
  {id:'arrigal',name:'Arrigal',place:'Acampamento Vistana de Vallaki',role:'Assassino Vistana · agente de Strahd',kind:'Antagonista',
    summary:'Assassino Vistana que, com o irmão Luvash, comanda o acampamento de Vallaki a serviço de Strahd. No gancho “Pedido de Ajuda”, entrega a carta falsa de Kolyan, escrita pelo conde.',
    detail:'Diz servir ao burgomestre Kolyan, mas obedece a Strahd. Tem uma alma corrompida.',
    tarokka:'Se a carta o indicar, aceita o destino e acompanha o grupo; se Strahd cair, trai os aventureiros, certo de que está destinado a governar Baróvia.'},
  {id:'luvash',name:'Luvash',place:'Acampamento Vistana de Vallaki',role:'Líder Vistana',kind:'Antagonista',
    summary:'Líder do acampamento Vistana de Vallaki ao lado do irmão Arrigal. Ambos são maus e fazem o que Strahd exigir.',
    detail:'Sua filha de sete anos, Arabelle, desapareceu e metade do acampamento a procura. Quem a devolver ganha o respeito e a gratidão dos Vistani. O acampamento também está sem vinho e vigia os elfos das sombras por ordem de Strahd.'},
  {id:'arabelle',name:'Arabelle',place:'Lago Zarovich · acampamento Vistana',role:'Criança Vistana',kind:'Aliada',
    summary:'Filha de sete anos de Luvash, raptada pelo pescador Bluto e prestes a ser afogada no Lago Zarovich como oferenda por uma boa pesca.',
    detail:'Descende de Madame Eva e tem sangue da realeza baroviana, embora não saiba de sua ligação com Strahd. Age mais como adulta do que como criança e acredita que um grande destino a espera.',
    tarokka:'Junta-se de bom grado ao grupo; se voltar ao acampamento, Luvash não permite que ela parta.'},
  {id:'stanimir',name:'Stanimir',place:'Fora de Baróvia · gancho de aventura',role:'Ancião Vistana',kind:'Neutra',
    summary:'Velho Vistana que lidera o grupo do gancho “Visitantes Misteriosos”. Conta, à fogueira, a história do príncipe amaldiçoado e convida os heróis a conhecer Madame Eva.',
    detail:'Viaja com a filha Damia, o filho Ratka e outros nove Vistani. Recebe o aviso da duquesa Morwen com uma gargalhada e só parte depois de contar sua história.'},
  {id:'alenka',name:'Alenka',place:'Vila de Baróvia',role:'Proprietária Vistana da taverna',kind:'Neutra',
    summary:'Uma das três mulheres Vistani donas da taverna Sangue da Videira. Elas espionam para Strahd e recomendam que os viajantes procurem Madame Eva.'},
  {id:'mirabel',name:'Mirabel',place:'Vila de Baróvia',role:'Proprietária Vistana da taverna',kind:'Neutra',
    summary:'Uma das três mulheres Vistani donas da taverna Sangue da Videira, que observam os forasteiros para Strahd.'},
  {id:'sorvia',name:'Sorvia',place:'Vila de Baróvia',role:'Proprietária Vistana da taverna',kind:'Neutra',
    summary:'Uma das três mulheres Vistani donas da taverna Sangue da Videira, que observam os forasteiros para Strahd.'},

  // ——— Elfos das sombras
  {id:'kasimir',name:'Kasimir Velikov',place:'Acampamento dos elfos sombrios',role:'Líder dos elfos sombrios',kind:'Aliado',
    summary:'Elfo das sombras que vive perto dos Vistani de Vallaki. Busca no Templo Âmbar um meio de trazer de volta a irmã Patrina, que ele mesmo ajudou a apedrejar.',
    detail:'Há séculos orquestrou o apedrejamento de Patrina para impedir que ela se tornasse esposa de Strahd. Em represália, Rahadin matou as elfas do clã, condenando o povo à extinção, e cortou as orelhas de Kasimir. Patrina lhe fala em sonhos. Ele espiona o Templo Âmbar há anos e acredita que lá está o segredo para quebrar o pacto de Strahd; mais ainda, para devolver a vida aos mortos. Precisa de aventureiros para sobreviver aos perigos do templo.',
    tarokka:'Só acompanha o grupo a Ravenloft depois de ser levado ao Templo Âmbar e encontrar um meio de ressuscitar Patrina.'},
  {id:'patrina',name:'Patrina Velikovna',place:'Castelo Ravenloft · passado',role:'Elfa sombria · arquimaga',kind:'Histórico',
    summary:'Elfa das sombras que revelou a Strahd a lenda do Templo Âmbar. Queria seu poder e acabou apedrejada pelo próprio povo antes de se tornar sua esposa.',
    detail:'Rahadin desconfiou dela desde o início e a afastou quando Strahd se encantou por Tatyana. Após a maldição, voltou ao castelo desejando ser noiva do conde. Strahd sepultou seu corpo nas criptas de Ravenloft, onde está seu livro de magias. Seu espírito visita Kasimir em sonhos.'},

  // ——— Vila de Baróvia e Casa da Morte
  {id:'madmage',name:'Mago Louco do Monte Baratok',aliases:['Mordenkainen'],place:'Monte Baratok',role:'Arquimago enlouquecido',kind:'Aliado',
    summary:'Arquimago que chegou a Baróvia há mais de um ano para libertar o povo, liderou uma revolta de aldeões contra Ravenloft e foi derrotado por Strahd. Na verdade, é Mordenkainen.',
    detail:'Perdeu a memória e vive paranoico, convencido de que agentes inimigos o vigiam. Lançou sobre si mesmo uma magia que impede a cura comum da loucura. Com o juízo restaurado, é teimoso e autoritário, oferece abrigo em uma mansão extradimensional e insiste que o Memorial, o Símbolo Sagrado e a Espada Solar sejam recuperados antes do confronto.',
    tarokka:'Com a sanidade restaurada, pode ser persuadido a lutar contra Strahd.'},
  {id:'mary',name:'Mary Maluca',place:'Vila de Baróvia',role:'Mãe de Gertruda',kind:'Neutra',
    summary:'Mulher desesperada que chora dia e noite pela filha Gertruda, que escondeu em casa a vida inteira e que fugiu há uma semana.',
    detail:'Guarda uma boneca deformada feita por Gadof Blinsky, que pertenceu a ela na juventude e depois a Gertruda. Teme o pior, e com razão: a filha está em Ravenloft.'},
  {id:'gertruda',name:'Gertruda',place:'Castelo Ravenloft',role:'Filha de Mary',kind:'Neutra',
    summary:'Adolescente criada trancada em casa. Fugiu para Ravenloft, atraída pela majestade do castelo, e foi enfeitiçada por Strahd.',
    detail:'Ingênua a ponto de ser um perigo para si mesma, tem uma visão de contos de fadas da vida e quase sempre faz a escolha mais simples. Não percebe o risco que corre.'},
  {id:'donavich',name:'Donavich',place:'Vila de Baróvia',role:'Sacerdote da vila',kind:'Neutra',
    summary:'Padre da igreja da vila, rouco e à beira da loucura. Mantém o filho Doru, transformado em cria vampírica, preso sob a igreja e reza por um jeito de salvá-lo.',
    detail:'Doru e outros aldeões invadiram Ravenloft atraídos pelo Mago Louco. Donavich tenta impedir quem queira destruir o filho e desaba em desespero se Doru morrer. É ele quem pode conduzir o funeral de Kolyan.',
    tarokka:'Só acompanha o grupo depois que Doru estiver morto e enterrado.'},
  {id:'doru',name:'Doru',place:'Vila de Baróvia',role:'Cria vampírica',kind:'Antagonista',
    summary:'Filho de Donavich. Pouco mais de um ano atrás, aos vinte anos, invadiu Ravenloft em uma revolta e voltou para o pai como cria vampírica.',
    detail:'Strahd o enviou para atormentar Donavich e expulsá-lo da igreja. Está faminto, preso no subterrâneo, e clama pelo pai sem parar. Se contido, pode narrar a queda da revolta.'},
  {id:'bildrath',name:'Bildrath Cantemir',place:'Vila de Baróvia',role:'Comerciante',kind:'Neutra',
    summary:'Dono do Mercadinho de Bildrath. Vende de tudo, mas cobra dos forasteiros dez vezes o preço normal e não negocia.'},
  {id:'parriwimple',name:'Parriwimple',aliases:['Parpol Cantemir'],place:'Vila de Baróvia',role:'Ajudante da loja',kind:'Neutra',
    summary:'Sobrinho de Bildrath, forte como um gladiador e um pouco lento de raciocínio. Seu nome verdadeiro é Parpol Cantemir, mas ninguém o usa.',
    tarokka:'Por ser meio bobo, não viaja a Ravenloft sem a permissão do tio Bildrath.'},
  {id:'arik',name:'Arik Lorensk',place:'Vila de Baróvia',role:'Barman da Sangue da Videira',kind:'Neutra',
    summary:'Homem baixo e gorducho que atende no bar da taverna com voz monótona, limpando copos sem parar e ignorando perguntas.'},
  {id:'lucianjarov',name:'Lucian Jarov',place:'Vila de Baróvia',role:'Menino de sete anos',kind:'Neutra',
    summary:'Menino que os próprios pais entregam a Morgantha como pagamento por pastéis de sonhos. A bruxa o leva num saco para o Velho Moedor de Ossos.'},
  {id:'morgantha',name:'Morgantha',place:'Velho Moedor de Ossos',role:'Bruxa da noite · vendedora de pastéis',kind:'Antagonista',
    summary:'Bruxa da noite que percorre a vila de Baróvia vendendo pastéis de sonhos. Com as filhas, forma um conventículo no Velho Moedor de Ossos.',
    detail:'Os pastéis levam o pó dos ossos de crianças moídos no moinho e fazem quem os come entrar num transe de felicidade. Quando os adultos não podem mais pagar, as bruxas aceitam os filhos deles como pagamento, semeando a corrupção no domínio de Strahd. Na vila, pode ser vista levando o menino Lucian Jarov num saco.'},
  {id:'bella',name:'Bella Perdição-do-Sol',place:'Velho Moedor de Ossos',role:'Bruxa da noite',kind:'Antagonista',
    summary:'Filha de Morgantha e parte do conventículo do Velho Moedor de Ossos. Ajuda a mãe e a irmã a produzir os pastéis de sonhos.'},
  {id:'offalia',name:'Offalia Vermes-Serpenteantes',place:'Velho Moedor de Ossos',role:'Bruxa da noite',kind:'Antagonista',
    summary:'Filha de Morgantha e parte do conventículo do Velho Moedor de Ossos. Ajuda a mãe e a irmã a produzir os pastéis de sonhos.'},
  {id:'kavan',name:'Kavan',place:'Colina Yester',role:'Antigo chefe bárbaro',kind:'Histórico',
    summary:'Chefe impiedoso da tribo Jived, séculos antes de Strahd. Dormia de dia, caçava à noite e bebia o sangue das presas; empunhava a primeira lança de sangue.',
    detail:'Seu espírito pode conduzir um aventureiro até seu túmulo e sua lança.'},
  {id:'dalvan',name:'Dalvan Olensky',place:'Estrada de Baróvia',role:'Mensageiro morto',kind:'Histórico',
    summary:'Tentava sair de Baróvia com uma carta de seu senhor, o burgomestre Kolyan, quando foi morto pelos lobos atrozes de Strahd.',
    detail:'Foi instruído a deixar a carta nos portões na esperança de atrair visitantes. O corpo, com a carta verdadeira de Kolyan, fica na estrada perto dos portões.'},
  {id:'rose',name:'Rosavalda Durst',aliases:['Rose'],place:'Casa da Morte',role:'Criança Durst · espírito',kind:'Neutra',
    summary:'Filha de dez anos de Gustav e Elisabeth. Na rua, ela e Thorn são ilusões criadas pela casa para atrair o grupo; dentro, seus espíritos ainda pedem ajuda.',
    detail:'Os pais a trancaram com o irmão num quarto do sótão até que morressem de fome. Acredita que há um monstro no porão e um bebê no berçário.'},
  {id:'thorn',name:'Thornboldt Durst',aliases:['Thorn'],place:'Casa da Morte',role:'Criança Durst · espírito',kind:'Neutra',
    summary:'Filho de sete anos de Gustav e Elisabeth, que chora abraçado a uma boneca. Morreu de fome com a irmã Rose, trancado no sótão.'},
  {id:'gustav',name:'Gustav Durst',place:'Casa da Morte',role:'Patriarca Durst · lívido',kind:'Antagonista',
    summary:'Patriarca da família rica que praticava artes sombrias e mantinha um culto na casa. Hoje é um lívido escondido nas paredes da masmorra.',
    detail:'Teve um filho, Walter, com a ama da casa. O culto sacrificava visitantes; quando capturou aventureiros que Strahd atraíra como brinquedos, o conde matou os cultistas.'},
  {id:'elisabeth',name:'Elisabeth Durst',place:'Casa da Morte',role:'Matriarca Durst · lívida',kind:'Antagonista',
    summary:'Matriarca da família e do culto da Casa da Morte. Hoje é uma lívida que ataca junto com Gustav quem mexe nos bens do culto.',
    detail:'Olhava com desprezo o bebê Walter, filho do marido com a ama. Os cultistas viam Strahd como um messias, mas ele os rejeitou como indignos.'},
  {id:'walter',name:'Walter Durst',place:'Casa da Morte',role:'Bebê da família Durst',kind:'Histórico',
    summary:'Filho de Gustav com a ama da casa. Rose e Thorn acreditam que ele está no berçário, mas isso é falso; sua cripta na masmorra está vazia.'},

  // ——— Vallaki
  {id:'vargas',name:'Barão Vargas Vallakovich',place:'Vallaki',role:'Burgomestre',kind:'Antagonista',
    summary:'Burgomestre de Vallaki. Impõe festivais semanais e o lema “Tudo ficará bem!”, convencido de que a felicidade forçada mantém Strahd longe.',
    detail:'Descende do fundador da cidade e acredita ter sangue nobre. Tem ego frágil, anda sempre de armadura e com dois mastins, e pune quem zomba dos festivais. Izek, seu capanga, impõe sua vontade. Chama os críticos de “espiões do diabo Strahd”. Fiona Wachter disputa o controle da cidade.'},
  {id:'lydia',name:'Lydia Petrovna',place:'Vallaki',role:'Baronesa',kind:'Neutra',
    summary:'Esposa de Vargas e mãe de Victor. Abraçou a filosofia de felicidade do marido a ponto de rir por reflexo nervoso e distribui chá e bolo aos pobres da cidade.',
    detail:'É temente aos deuses, irmã mais nova do Padre Lucian e descendente de Tasha Petrovna. Possui um belo vestido de noiva branco que o Abade de Krezk deseja para Vasilka; ela o cederia, mas o barão não permite.'},
  {id:'victor',name:'Victor Vallakovich',place:'Vallaki',role:'Filho do burgomestre · aprendiz de magia',kind:'Neutra',
    summary:'Filho de Vargas e Lydia, isolado no sótão da mansão. Aprendeu magia sozinho com um livro antigo e constrói um círculo de teletransporte para fugir de Baróvia.',
    detail:'É estranho, amargo e perigoso. Anima esqueletos de gatos para praticar e finge que bonecos de madeira são seus alunos. Humilhou Stella Wachter quando Fiona tentou aproximá-la dele.',
    tarokka:'Percebe que o grupo é a chave para sua salvação e acompanha os aventureiros com entusiasmo.'},
  {id:'izek',name:'Izek Strazni',place:'Vallaki',role:'Capitão da guarda',kind:'Antagonista',
    summary:'Capanga brutal do barão, com um braço monstruoso. É obcecado por uma jovem que vê em sonhos: Ireena, sua irmã perdida.',
    detail:'Encomendou a Blinsky bonecas com o rosto de Ireena e as guarda em seu quarto. Nem ele nem Ireena sabem que são irmãos. Ao vê-la, tenta levá-la à força. Carrega as chaves dos grilhões da praça e procura os criados que desapareceram da mansão.'},
  {id:'fiona',name:'Lady Fiona Wachter',place:'Vallaki',role:'Nobre rival do barão',kind:'Antagonista',
    summary:'Nobre que planeja derrubar Vargas e governar Vallaki. Declara abertamente que não é, nem será, inimiga de Strahd, e mantém um culto secreto em casa.',
    detail:'Sua família apoia Strahd há gerações e guarda uma carta de agradecimento de “Vasili von Holtz” a uma antepassada. Dorme com o cadáver preservado do marido Nikolai, morto há quase três anos. Usou a filha Stella como peão para chegar à mansão do barão. Oferece ajuda a quem matar Izek. Os Wachter guardam os ossos de Leo Dilisnya para que ele nunca seja reerguido.'},
  {id:'nikolaiold',name:'Nikolai Wachter',place:'Vallaki',role:'Marido falecido de Fiona',kind:'Histórico',
    summary:'Lorde Nikolai Wachter morreu de doença há quase três anos. Fiona conserva o corpo com magia e dorme ao lado dele.',
    detail:'Embora a família sempre tenha apoiado Strahd, no fim da vida ele concluiu que o conde precisa ser destruído para salvar Baróvia.',
    tarokka:'Se for trazido de volta com reviver os mortos ou ressurreição, ajuda o grupo apesar dos protestos da esposa. Rictavio pode fornecer o pergaminho.'},
  {id:'nikolai',name:'Nikolai Wachter, filho',place:'Vallaki',role:'Filho de Fiona',kind:'Neutra',
    summary:'Jovem nobre, tolo e orgulhoso, que passa o tempo bebendo na Estalagem Água Azul com o irmão Karl. Numa noite de festival, os dois libertam sem querer o tigre de Rictavio.'},
  {id:'karl',name:'Karl Wachter',place:'Vallaki',role:'Filho de Fiona',kind:'Neutra',
    summary:'Irmão de Nikolai, igualmente tolo e presunçoso. Os dois bebem na Estalagem Água Azul e causam problemas nos festivais.'},
  {id:'stella',name:'Stella Wachter',place:'Vallaki',role:'Filha de Fiona',kind:'Neutra',
    summary:'Filha enlouquecida de Fiona, trancada em casa, que acredita ser um gato. Uma restauração maior devolve sua sanidade.',
    detail:'Fiona tentou aproximá-la de Victor para conquistar a mansão do barão, mas ele não teve interesse e a humilhou. Curada, culpa a mãe por usá-la como peão, encolhe-se ao ouvir o nome de Victor e se apega a quem for gentil. O Padre Lucian se oferece para cuidar dela.',
    tarokka:'Não traz benefício algum enquanto estiver louca; curada, junta-se ao grupo com prazer e deixa a família para trás.'},
  {id:'ernst',name:'Ernst Larnak',place:'Vallaki',role:'Espião de Fiona',kind:'Antagonista',
    summary:'Espião e conselheiro de Lady Wachter. Escuta escondido as conversas da senhora com os visitantes para aconselhá-la depois.'},
  {id:'lucian',name:'Padre Lucian Petrovich',place:'Vallaki',role:'Sacerdote de Santo Andral',kind:'Aliado',
    summary:'Sacerdote da igreja de Santo Andral. Todas as noites oferece orações e proteção à congregação, mas os ossos do santo que protegiam a igreja foram roubados.',
    detail:'Era o único que sabia dos ossos, mas comentou o segredo com o coroinha Yeska. Sem as relíquias, a igreja fica vulnerável ao ataque das crias vampíricas. É irmão mais velho da baronesa Lydia e pode acolher Stella Wachter.'},
  {id:'andral',name:'Santo Andral',place:'Vallaki · igreja',role:'Santo do passado',kind:'Histórico',
    summary:'Santo cujos ossos, selados sob o altar da igreja de Vallaki, protegiam o lugar de Strahd. Foram roubados por Milivoj a mando de Henrik van der Voort.',
    detail:'Um dos vitrais da abadia de Krezk o retrata ao lado do Senhor da Alvorada e de Santa Markóvia. Os ossos estão num compartimento secreto na oficina de Henrik; devolvê-los antes do ataque das crias vampíricas é uma corrida contra o tempo.'},
  {id:'yeska',name:'Yeska',place:'Vallaki',role:'Coroinha',kind:'Neutra',
    summary:'Menino órfão que ajuda o Padre Lucian. Soube dos ossos de Santo Andral e contou o segredo a Milivoj.'},
  {id:'milivoj',name:'Milivoj',place:'Vallaki',role:'Coveiro da igreja',kind:'Neutra',
    summary:'Rapaz musculoso e carrancudo que cuida da igreja. Desenterrou os ossos de Santo Andral e os vendeu a Henrik para alimentar os irmãos mais novos.',
    detail:'Confessa sob intimidação. Arrancou o piso da capela com a pá para chegar à cripta e recolocou as tábuas.'},
  {id:'henrik',name:'Henrik van der Voort',place:'Vallaki',role:'Fabricante de caixões',kind:'Antagonista',
    summary:'Fabricante de caixões que abriga em sua oficina um ninho de crias vampíricas, antigos aventureiros transformados por Strahd.',
    detail:'Meses atrás, Strahd o visitou disfarçado de Vasili von Holtz e prometeu “bons negócios”. As crias ordenaram que ele conseguisse os ossos de Santo Andral, e ele pagou Milivoj pelo roubo. Os vampiros planejam atacar a igreja durante um festival.'},
  {id:'udo',name:'Udo Lukovich',place:'Vallaki',role:'Sapateiro preso',kind:'Neutra',
    summary:'Sapateiro preso no Festival da Cabeça de Lobo por sugerir aos vallakianos que dessem o barão de comer aos lobos.',
    detail:'Se libertado, quer voltar para casa e denunciar ao Padre Lucian os maus-tratos sofridos. Sob coação, entrega quem o libertou.'},
  {id:'willemina',name:'Willemina Rikalova',place:'Vallaki',role:'Mãe de Udo',kind:'Neutra',
    summary:'Velha triste que reza todas as noites na igreja de Santo Andral para que o filho seja libertado.'},
  {id:'lars',name:'Lars Kjurls',place:'Vallaki',role:'Guarda da milícia',kind:'Neutra',
    summary:'Guarda da milícia que solta uma risada fora de hora durante um festival. O barão o prende “por despeito” e ameaça arrastá-lo atrás do cavalo.'},
  {id:'bluto',name:'Bluto Krogarov',place:'Lago Zarovich',role:'Pescador bêbado',kind:'Antagonista',
    summary:'Pescador miserável e bêbado que não pega um peixe há uma semana. Raptou Arabelle, acreditando que Vistani trazem sorte, e pretende afogá-la no lago em troca de peixes.'},
  {id:'szoldar',name:'Szoldar Szoldarovich',place:'Vallaki',role:'Caçador de lobos',kind:'Neutra',
    summary:'Caçador sério que, com o parceiro Yevgeni, guia viajantes pelos bosques mediante pagamento.'},
  {id:'yevgeni',name:'Yevgeni Krushkin',place:'Vallaki',role:'Caçador de lobos',kind:'Neutra',
    summary:'Caçador que trabalha como guia ao lado de Szoldar.'},
  {id:'blinsky',name:'Gadof Blinsky',place:'Vallaki',role:'Fabricante de brinquedos',kind:'Neutra',
    summary:'Artesão de brinquedos macabros, com a etiqueta “Se não é divertido, não é Blinsky!”.',
    detail:'Fez as bonecas com o rosto de Ireena encomendadas por Izek e, anos antes, a boneca da família de Mary Maluca. Ganhou de Rictavio o macaco Piccolo. Seus brinquedos aparecem até no covil dos lobisomens.'},
  {id:'piccolo',name:'Piccolo',place:'Vallaki',role:'Macaco',kind:'Neutra',
    summary:'Macaco que Rictavio deu de presente a Gadof Blinsky.'},
  {id:'gunther',name:'Gunther Arasek',place:'Vallaki',role:'Comerciante',kind:'Neutra',
    summary:'Administra com Yelena o pátio de estocagem Arasek, onde está guardada a carroça trancada de Rictavio, com seu tigre-dentes-de-sabre.'},
  {id:'yelena',name:'Yelena Arasek',place:'Vallaki',role:'Comerciante',kind:'Neutra',
    summary:'Administra com Gunther o pátio de estocagem Arasek, que guarda a carroça de Rictavio.'},
  {id:'leo',name:'Leo Dilisnya',place:'Vallaki · passado',role:'Traidor de Strahd',kind:'Histórico',
    summary:'Um dos guardas que atiraram flechas em Strahd na noite do casamento. Fugiu de Ravenloft, mas foi caçado e morto pelo vampiro.',
    detail:'Os Wachter guardam seus ossos num cofre forrado de chumbo para que ele nunca seja reerguido.'},

  // ——— Martikov e Guardiões da Pena
  {id:'urwin',name:'Urwin Martikov',place:'Vallaki',role:'Estalajadeiro · Guardião da Pena',kind:'Aliado',
    summary:'Dono da Estalagem Água Azul, homem-corvo e membro de alto escalão dos Guardiões da Pena, sociedade secreta que se opõe a Strahd.',
    detail:'Pede ao grupo que descubra por que a remessa de vinho do Mago dos Vinhos atrasou, como teste de confiança. Abriga Rictavio. O pai, Davian, o culpa pelo desaparecimento da primeira gema mágica da vinícola: Urwin estava de vigia naquela noite e, segundo Davian, foi ver a noiva. Urwin sempre negou.'},
  {id:'danika',name:'Danika Dorakova',place:'Vallaki',role:'Estalajadeira · Guardiã da Pena',kind:'Aliada',
    summary:'Esposa e sócia de Urwin na Estalagem Água Azul. Também é mulher-corvo e protege a família e a sociedade secreta.'},
  {id:'brom',name:'Brom Martikov',place:'Vallaki',role:'Filho de Urwin e Danika',kind:'Neutra',
    summary:'Um dos dois filhos de Urwin e Danika, de nove e onze anos. É homem-corvo, jovem demais para lutar.'},
  {id:'bray',name:'Bray Martikov',place:'Vallaki',role:'Filho de Urwin e Danika',kind:'Neutra',
    summary:'Um dos dois filhos de Urwin e Danika, de nove e onze anos. É homem-corvo, jovem demais para lutar.'},
  {id:'davian',name:'Davian Martikov',place:'Mago dos Vinhos',role:'Patriarca Martikov',kind:'Aliado',
    summary:'Velho desconfiado que administra a vinícola Mago dos Vinhos e lidera a família de homens-corvo. Druidas e infectados tomaram a adega e as três gemas mágicas que mantinham o vinhedo vivo sumiram.',
    detail:'Culpa o filho Urwin pela perda da primeira gema. A segunda está com Baba Lysaga e a terceira foi levada pelos druidas para a Colina Yester. Sem as gemas, o vinhedo morre e o vale fica sem vinho.',
    tarokka:'Deixa a vinícola com Adrian e Elvir para enfrentar Strahd, mas antes insiste em se reconciliar com Urwin.'},
  {id:'adrian',name:'Adrian Martikov',place:'Mago dos Vinhos',role:'Filho de Davian',kind:'Aliado',
    summary:'Filho de Davian e homem-corvo. Ajuda a defender e a administrar a vinícola; herdaria o negócio com Elvir se o pai partisse.'},
  {id:'elvir',name:'Elvir Martikov',place:'Mago dos Vinhos',role:'Filho de Davian',kind:'Aliado',
    summary:'Filho de Davian e homem-corvo. Ajuda a família no Mago dos Vinhos e no transporte do vinho.'},
  {id:'stefania',name:'Stefania Martikov',place:'Mago dos Vinhos',role:'Filha de Davian',kind:'Aliado',
    summary:'Filha de Davian, mulher-corvo e membro dos Guardiões da Pena. Refugia-se com a família na floresta perto da vinícola, com o marido Dag e os quatro filhos.'},
  {id:'dag',name:'Dag Tomescu',place:'Mago dos Vinhos',role:'Marido de Stefania',kind:'Aliado',
    summary:'Homem-corvo casado com Stefania e membro dos Guardiões da Pena, que ajuda a defender a vinícola.'},
  {id:'claudiu',name:'Claudiu',place:'Mago dos Vinhos',role:'Neto de Davian',kind:'Neutra',
    summary:'Filho adolescente de Stefania e Dag, homem-corvo.'},
  {id:'martin',name:'Martin',place:'Mago dos Vinhos',role:'Neto de Davian',kind:'Neutra',
    summary:'Filho de Stefania e Dag; homem-corvo ainda criança, não combatente.'},
  {id:'viggo',name:'Viggo',place:'Mago dos Vinhos',role:'Neto de Davian',kind:'Neutra',
    summary:'Filho de Stefania e Dag; homem-corvo ainda criança, não combatente.'},
  {id:'yolanda',name:'Yolanda',place:'Mago dos Vinhos',role:'Neta de Davian',kind:'Neutra',
    summary:'Filha caçula de Stefania e Dag. Ainda não consegue mudar de forma e, na prática, é uma criança humana.'},
  {id:'muriel',name:'Muriel Vinshaw',place:'Ruínas de Berez',role:'Guardiã da Pena',kind:'Aliado',
    summary:'Mulher-corvo de Vallaki e amiga dos Martikov. Espiona Baba Lysaga dos arredores de Berez e alerta os aventureiros sobre a bruxa.',
    detail:'Evita combate e esconde sua natureza. Não enfrenta Baba Lysaga com o grupo, mas indica Argynvostholt e a Colina Yester e conhece a história dos druidas que passaram a adorar Strahd.'},

  // ——— Krezk e a abadia
  {id:'dmitri',name:'Dmitri Krezkov',place:'Krezk',role:'Burgomestre',kind:'Aliado',
    summary:'Burgomestre de Krezk, de família nobre. Só abre os portões da vila a quem traz vinho ou prova boa-fé. Esconde o luto pelo filho Ilya, o último de quatro.',
    detail:'Ilya, de catorze anos, morreu de doença. Dmitri desconfia do Abade, mas pode ser tentado a pedir que ele traga o filho de volta.'},
  {id:'anna',name:'Anna Krezkova',place:'Krezk',role:'Esposa do burgomestre',kind:'Aliado',
    summary:'Esposa de Dmitri e mãe de Ilya. Devota, é chamada para abençoar partos na ausência de um padre e louva o Abade e Santa Markóvia.'},
  {id:'ilya',name:'Ilya Krezkov',place:'Krezk',role:'Filho dos Krezkov',kind:'Histórico',
    summary:'Filho de catorze anos de Dmitri e Anna, morto recentemente por doença. O Abade pode revivê-lo, num evento que muda a visão da família sobre ele.'},
  {id:'abbot',name:'O Abade',place:'Abadia de Santa Markóvia',role:'Deva corrompido',kind:'Antagonista',
    summary:'Deva milenar enviado para honrar o legado de Santa Markóvia, que reabriu a abadia há mais de um século. Os Poderes Sombrios o corromperam, e hoje ele quer “curar” Strahd com uma noiva.',
    detail:'Ao tentar livrar a família Belview de suas imperfeições, aceitou a ajuda de Vasili von Holtz, que trouxe um saber proibido do Templo Âmbar e revelou ser Strahd. Juntos, transformaram os Belview em párias. Convencido de que reunir Strahd ao amor perdido acabará com a maldição, criou Vasilka e procura um vestido de noiva para ela. Muitos em Krezk suspeitam que o Abade seja Strahd disfarçado, mas a verdade é mais perturbadora.'},
  {id:'vasilka',name:'Vasilka',place:'Abadia de Santa Markóvia',role:'Golem de carne',kind:'Neutra',
    summary:'Noiva de carne costurada pelo Abade com partes de mulheres mortas, destinada a Strahd. Recebe aulas de etiqueta para ser apresentada ao conde.',
    detail:'Strahd não tem interesse nela; apenas se diverte corrompendo o anjo que a criou.',
    tarokka:'Pode ser o aliado indicado pelas cartas.'},
  {id:'clovin',name:'Clovin Belview',place:'Abadia de Santa Markóvia',role:'Pária de duas cabeças',kind:'Neutra',
    summary:'Pária de duas cabeças, servo fiel do Abade por medo e lealdade distorcida. Toca o sino do jantar e leva comida aos outros párias, que ele despreza.',
    detail:'É o único a quem Marzena permite chegar perto.',
    tarokka:'Enquanto o Abade viver, hesita em despertar a ira do senhor; pode acompanhar o grupo se a leitura o indicar.'},
  {id:'otto',name:'Otto Belview',place:'Abadia de Santa Markóvia',role:'Pária · porteiro',kind:'Neutra',
    summary:'Pária que, com Zygfrek, guarda o portão e cava as covas da abadia. É servo leal do Abade, embora pouco atento como guarda.'},
  {id:'zygfrek',name:'Zygfrek Belview',place:'Abadia de Santa Markóvia',role:'Pária · porteira',kind:'Neutra',
    summary:'Pária que, com Otto, guarda o portão e cava as covas da abadia, sempre leal ao Abade.'},
  {id:'mishka',name:'Mishka Belview',place:'Abadia de Santa Markóvia',role:'Pária do poço',kind:'Antagonista',
    summary:'Pária com três olhos de aranha, mão de rã e pé de corvo, escondido no poço da abadia. Ataca quem ilumina seu esconderijo.'},
  {id:'marzena',name:'Marzena Belview',place:'Abadia de Santa Markóvia',role:'Pária alada',kind:'Neutra',
    summary:'Irmã mais velha de Mishka, acorrentada a um poste no pátio. Voa, teme a todos e está convencida de que inimigos poderosos a vigiam; só deixa Clovin alimentá-la.'},
  {id:'markovia',name:'Santa Markóvia',place:'Abadia de Santa Markóvia',role:'Santa do passado',kind:'Histórico',
    summary:'Sacerdotisa do Senhor da Alvorada que destruiu os vampiros enviados à sua abadia e invadiu Ravenloft. Nunca voltou; Strahd passou a mancar.',
    detail:'Diz-se que jaz numa cripta sob o castelo. Seu fêmur ganhou poder contra mortos-vivos. A abadia e o poço abençoado de Krezk guardam seu legado.'},

  // ——— Argynvostholt
  {id:'argynvost',name:'Argynvost',place:'Argynvostholt',role:'Dragão de prata',kind:'Histórico',
    summary:'Dragão de prata que viveu entre os homens como Lorde Argynvost. Veio ao vale para vigiar o Templo Âmbar e fundou a Ordem do Dragão de Prata.',
    detail:'Na guerra, a Ordem abrigou os inimigos de Strahd e foi esmagada; o dragão lutou até o fim diante da mansão. Strahd levou seu esqueleto a Ravenloft como troféu. Devolver o crânio e acender o farol de Argynvostholt permite que os cavaleiros descansem.'},
  {id:'vladimir',name:'Vladimir Horngaard',place:'Argynvostholt',role:'Comandante ressurgido',kind:'Antagonista',
    summary:'Líder dos cavaleiros mortos-vivos da Ordem do Dragão de Prata. Odeia Strahd, mas não quer que o tormento dele termine.',
    detail:'Comandante de campo de Argynvost, viu Strahd matar seu amado Sir Godfrey antes de cair. Voltou como ressurgido e trouxe outros cavaleiros consigo. Quando marchou contra Ravenloft, Katarina lhe disse que Strahd já estava morto e aprisionado; Vladimir recuou e desde então mata quem possa aliviar o sofrimento do conde. Sua redenção depende de abandonar esse ódio.'},
  {id:'godfrey',name:'Sir Godfrey Gwilym',place:'Argynvostholt',role:'Cavaleiro ressurgido',kind:'Aliado',
    summary:'Cavaleiro ressurgido e paladino da Ordem do Dragão de Prata, morto por Strahd diante de Vladimir, seu amado em vida.',
    detail:'Sente que o espírito de Argynvost não descansa e se entristece com o estado da Ordem. Pode contar aos aventureiros a história de sua ascensão e queda.',
    tarokka:'Relutante no início; acompanha o grupo se for convencido de que a honra da Ordem pode ser restaurada.'},

  // ——— Berez
  {id:'marina',name:'Marina',place:'Berez · passado',role:'Reencarnação de Tatyana',kind:'Histórico',
    summary:'Plebeia de Berez igual a Tatyana no rosto e nos modos. Strahd a seduziu e bebeu seu sangue; para salvar sua alma, Lazlo e Grigor a mataram.',
    detail:'Em vingança, Strahd matou os dois e inundou a vila, que virou pântano. Há um memorial a ela nas ruínas.'},
  {id:'lazlo',name:'Lazlo Ulrich',place:'Ruínas de Berez',role:'Antigo burgomestre · fantasma',kind:'Histórico',
    summary:'Burgomestre de Berez que, com o Irmão Grigor, matou Marina para impedir que ela se tornasse cria de Strahd. O conde o matou e afogou a vila.'},
  {id:'grigor',name:'Irmão Grigor',place:'Berez · passado',role:'Sacerdote',kind:'Histórico',
    summary:'Sacerdote de Berez que ajudou Lazlo a matar Marina para salvar sua alma e foi morto por Strahd em represália.'},

  // ——— Lobisomens
  {id:'kiril',name:'Kiril Stoyanovich',place:'Covil dos Lobisomens',role:'Líder da matilha',kind:'Antagonista',
    summary:'Chefe dos lobisomens de Baróvia, apoiado por Strahd. Faz crianças sequestradas lutarem até restar uma, que então transforma em lobisomem.',
    detail:'Emil propôs transformar todas as crianças para aumentar a matilha. Kiril sumiu por dias e voltou com dezenas de lobos atrozes de Strahd, que levaram Emil para Ravenloft. Bianca é sua companheira; Zuleika quer sua morte.'},
  {id:'emil',name:'Emil Toranescu',place:'Castelo Ravenloft · masmorra',role:'Lobisomem prisioneiro',kind:'Neutra',
    summary:'Lobisomem que desafiou os métodos de Kiril e foi levado prisioneiro a Ravenloft. Finge ser um morador de Vallaki perseguido por lobos e implora por resgate.'},
  {id:'zuleika',name:'Zuleika Toranescu',place:'Covil dos Lobisomens',role:'Lobisomem',kind:'Aliado',
    summary:'Companheira de Emil. Quer vingá-lo e ver Kiril morto.',
    tarokka:'Acompanha o grupo se os aventureiros prometerem vingar Emil matando Kiril.'},
  {id:'bianca',name:'Bianca',place:'Covil dos Lobisomens',role:'Lobisomem',kind:'Antagonista',
    summary:'Lobisomem de pelo branco, companheira de Kiril. Reage rápido a qualquer alarme e ataca intrusos.'},
  {id:'skennis',name:'Skennis',place:'Covil dos Lobisomens',role:'Lobisomem idoso',kind:'Neutra',
    summary:'Lobisomem velho demais para caçar, que toca mal uma flauta de electrum cercado de lobos. Luta até a morte para defender o covil.'},
  {id:'wensencia',name:'Wensencia',place:'Covil dos Lobisomens',role:'Lobisomem',kind:'Antagonista',
    summary:'Lobisomem encarregada de treinar Kellen. Ao soar o alarme, tranca a menina numa cela e se junta à defesa do covil.'},
  {id:'kellen',name:'Kellen',place:'Covil dos Lobisomens',role:'Criança lobisomem',kind:'Neutra',
    summary:'Menina de dez anos sequestrada do Domínio de Liam, nos Reinos Esquecidos. Venceu um dos torneios de Kiril e foi infectada.',
    detail:'Abraça uma boneca de Blinsky parecida com um dos aventureiros. Uma restauração maior ou remover maldição cura sua licantropia.'},

  // ——— Templo Âmbar
  {id:'exethanter',name:'Exethanter',place:'Templo Âmbar',role:'Lich',kind:'Neutra',
    summary:'Arquimago que violou o Templo Âmbar, aprendeu com um vestígio a se tornar lich e passou a guardar o templo para compartilhar seus segredos. Sua memória e magia se deterioraram.',
    detail:'Pressentiu que Strahd era um homem marcado pelo destino quando ele chegou ao templo em busca de imortalidade.'},
  {id:'neferon',name:'Neferon',place:'Templo Âmbar',role:'Arcanaloth guardião',kind:'Antagonista',
    summary:'Arcanaloth que guarda o templo de dentro da cabeça da grande estátua, envolto em escuridão mágica, e ataca de longe com magias.'},
  {id:'vilnius',name:'Vilnius',place:'Templo Âmbar',role:'Aprendiz de mago',kind:'Neutra',
    summary:'Aprendiz covarde, ganancioso e traiçoeiro, escondido no templo depois que caveiras flamejantes incineraram seu mestre, Jakarion. Sobrevive comendo vermes.',
    detail:'Quer recuperar o cajado e o livro de magias do mestre. Carrega, sem saber, o amuleto que controla um guardião do escudo do templo.'},
  {id:'jakarion',name:'Jakarion',place:'Templo Âmbar',role:'Mago falecido',kind:'Histórico',
    summary:'Mago que trouxe o aprendiz Vilnius a Baróvia e morreu incinerado no Templo Âmbar.'},
  {id:'khazan',name:'Khazan',place:'Castelo Ravenloft · catacumbas',role:'Arquimago',kind:'Histórico',
    summary:'Arquimago que ajudou a erguer Ravenloft e depois construiu a torre do Lago Baratok, hoje usada por van Richten.',
    detail:'A mando de Strahd, separou o punho e a lâmina da espada de Sergei; o aprendiz fugiu com o punho, que virou a Espada Solar, e Khazan mentiu dizendo que tudo fora destruído. Tentou se tornar um demilich para escapar do domínio e se destruiu. Seus restos estão nas catacumbas, onde dizer seu nome faz surgir um cajado de poder. Sua torre ainda guarda proteções e armadilhas mágicas.'},

  // ——— Castelo Ravenloft
  {id:'escher',name:'Escher',place:'Castelo Ravenloft',role:'Consorte de Strahd',kind:'Antagonista',
    summary:'Cria vampírica, consorte que já gozou do favor de Strahd. Inteligente e melancólico, anda se sentindo abandonado.',
    detail:'Teme que Strahd tenha se entediado dele e o tranque nas catacumbas com os outros consortes rejeitados. Se atacado, foge pelo telhado e leva os perseguidores até o mestre.'},
  {id:'ludmilla',name:'Ludmilla Vilisevic',place:'Castelo Ravenloft · túmulo de Strahd',role:'Noiva de Strahd',kind:'Antagonista',
    summary:'Uma das três noivas vampíricas que guardam o caixão de Strahd, de vestido de noiva branco sujo e tiara de ouro.'},
  {id:'anastrasya',name:'Anastrasya Karelova',place:'Castelo Ravenloft · túmulo de Strahd',role:'Noiva de Strahd',kind:'Antagonista',
    summary:'Uma das três noivas vampíricas que guardam o caixão de Strahd, de vestido vermelho esfarrapado e lenço de seda cravejado de joias.'},
  {id:'volenta',name:'Volenta Popofsky',place:'Castelo Ravenloft · túmulo de Strahd',role:'Noiva de Strahd',kind:'Antagonista',
    summary:'Uma das três noivas vampíricas que guardam o caixão de Strahd, de vestido dourado desbotado e máscara de platina em forma de caveira.'},
  {id:'sasha',name:'Sasha Ivliskova',place:'Castelo Ravenloft · cripta',role:'Esposa de Strahd',kind:'Antagonista',
    summary:'Cria vampírica registrada como “esposa” em sua cripta. Ataca quando percebe que quem entrou não é o marido.'},
  {id:'helga',name:'Helga Ruvak',place:'Castelo Ravenloft',role:'Criada · cria vampírica',kind:'Antagonista',
    summary:'Criada que diz ser a filha sequestrada do sapateiro da vila e implora para ser salva. É mesmo filha dele, mas escolheu uma vida de maldade ao lado de Strahd.',
    detail:'Junta-se ao grupo se convidada e espera uma oportunidade para atacar, ou a ordem de Strahd. Usa um colar de rubi de quase cinco séculos, presente do conde.'},
  {id:'cyrus',name:'Cyrus Belview',place:'Castelo Ravenloft',role:'Cozinheiro e criado',kind:'Antagonista',
    summary:'Pária que serve Strahd como cozinheiro e faz-tudo do castelo. Conhece a palavra de comando do portão, cria ratos como bichos de estimação e montou esculturas com ossos de mortos.'},
  {id:'lief',name:'Lief Lipsiege',place:'Castelo Ravenloft',role:'Contador do castelo',kind:'Neutra',
    summary:'Contador acorrentado à mesa em Ravenloft, indiferente aos visitantes. Puxa a corda de alarme se ameaçado e não sai da sala por vontade própria.',
    detail:'Mantém os livros de riquezas e conquistas de Strahd e se ressente de não conhecer todos os tesouros do mestre. Tratado com bondade, revela o esconderijo do Símbolo Sagrado do Corvo-Bondoso indicado pela leitura de tarokka e desenha um mapa até lá. Esqueceu que escondeu a chave dos quatro cofres da sala num livro manchado de sangue.'},
  {id:'pidlwick',name:'Pidlwick II',place:'Castelo Ravenloft',role:'Boneco mecânico',kind:'Neutra',
    summary:'Réplica mecânica do bobo Pidlwick, feita pelo fabricante Fritz von Weerg. Não fala, quer desesperadamente agradar e se esconde pelo castelo.',
    detail:'Empurrou o Pidlwick original escada abaixo e, por anos, sufocou hóspedes durante o sono. Strahd percebeu e o manteve para livrar-se de convidados incômodos. Teme o conde e segue quem lhe der atenção; quando está chateado, faz coisas ruins.',
    tarokka:'Pode ser o aliado indicado pelas cartas.'},
  {id:'pidlwick_first',name:'Pidlwick',place:'Castelo Ravenloft · fantasma',role:'Bobo da corte',kind:'Neutra',
    summary:'Bobo da duquesa Dorfniya que alegrava Sergei e Tatyana. Morreu empurrado da escada por sua réplica; seu fantasma ainda aparece no castelo.',
    detail:'O fantasma indica sua cripta como lugar de um tesouro e, se Pidlwick II estiver com o grupo, aponta: “Ele me empurrou pelas escadas”.'},
  {id:'beucephalus',name:'Beucephalus',place:'Castelo Ravenloft',role:'Corcel de Strahd',kind:'Antagonista',
    summary:'Pesadelo que serve de montaria a Strahd, com cripta própria nas catacumbas.'},
  {id:'lorde_klutz',name:'Lorde Klutz Tripalotsky',place:'Castelo Ravenloft · cripta',role:'Guerreiro fantasma',kind:'Histórico',
    summary:'Morreu caindo sobre a própria espada, anos antes de Strahd se tornar vampiro. Quem tira a espada de sua armadura o liberta como guerreiro fantasma, que luta ao seu lado por sete dias.',
    tarokka:'Se for o aliado das cartas, não desaparece após sete dias, apenas quando cair em combate.'},
  {id:'tasha',name:'Tasha Petrovna',place:'Castelo Ravenloft · cripta',role:'Sacerdotisa',kind:'Histórico',
    summary:'Lembrada como “Curadora dos Reis, Luz do Ocidente”. Seu símbolo sagrado abre um túmulo da família Petrovna em Krezk.',
    detail:'É antepassada da baronesa Lydia e do Padre Lucian.'},
  {id:'dorfniya',name:'Duquesa Dorfniya Dilisnya',place:'Castelo Ravenloft · cripta',role:'Nobre falecida',kind:'Histórico',
    summary:'Viúva que se tornou noiva de Strahd sem conquistar seu amor. Visitava o castelo com o bobo Pidlwick e encomendou a réplica Pidlwick II como presente.',
    detail:'Um inverno rigoroso a prendeu em Ravenloft por meses; morreu de doença ali.'},
  {id:'stefan_gregorovich',name:'Stefan Gregorovich',place:'Castelo Ravenloft · cripta',role:'Conselheiro real',kind:'Histórico',
    summary:'Primeiro conselheiro do rei Barov, sepultado nas criptas de Ravenloft.'},
  {id:'ciril',name:'Ciril Romulich',place:'Castelo Ravenloft · cripta',role:'Sumo sacerdote',kind:'Histórico',
    summary:'Sumo sacerdote, amado pelo rei Barov e pela rainha Ravenovia. Como arcebispo, deu a Strahd o Ícone de Ravenloft para consagrar o castelo.'},
  {id:'lorde_lee',name:'Lorde Leonid Krushkin',aliases:['Lorde Lee, o Esmagador'],place:'Castelo Ravenloft · cripta',role:'Nobre falecido',kind:'Histórico',
    summary:'Nobre de grande estatura que “mais que a vida, amava suas joias”, sepultado com elas nas criptas.'},
  {id:'lorde_erik',name:'Lorde Erik Vonderbucks',place:'Castelo Ravenloft · cripta',role:'Nobre falecido',kind:'Histórico',
    summary:'Nobre rico cujo cadáver foi coberto de ouro conforme seu último desejo.'},
  {id:'dostron',name:'Rei Dostron',aliases:['Dostron, o Nascido do Inferno'],place:'Castelo Ravenloft · cripta',role:'Antigo rei',kind:'Histórico',
    summary:'Governante desta terra muito antes de Strahd, que se dizia descendente de um duque dos Nove Infernos. Um diabrete invisível ainda vigia seus restos.'},
  {id:'jarnwald',name:'Lorde Jarnwald',aliases:['Jarnwald, o Vigarista'],place:'Castelo Ravenloft · cripta',role:'Nobre falecido',kind:'Histórico',
    summary:'“O gracejo estava sobre ele”: foi empurrado para dentro da própria cripta e devorado por carniçais.'},
  {id:'troisky',name:'Rei Troisky',place:'Castelo Ravenloft · cripta',role:'Antigo rei',kind:'Histórico',
    summary:'“O Rei de Três Faces”, sepultado com seu elmo de três visores: um triste, um feliz e um irado.'},
  {id:'katsky',name:'Rei Katsky',aliases:['Katsky, o Brilhante'],place:'Castelo Ravenloft · cripta',role:'Antigo rei',kind:'Histórico',
    summary:'Soberano, inventor e autoproclamado viajante do tempo, segundo a inscrição de sua cripta.'},
  {id:'stahbal',name:'Stahbal Indi-Bhak',place:'Castelo Ravenloft · cripta',role:'Amigo da coroa',kind:'Histórico',
    summary:'“Um amigo mais verdadeiro que qualquer governante já teve.” Sua cripta guarda os ossos de serviçais que juraram vingança contra sua família.'},
  {id:'artimus',name:'Artimus',place:'Castelo Ravenloft · cripta',role:'Construtor do forte',kind:'Histórico',
    summary:'Chamado de “Construtor do Forte” na inscrição de sua cripta.'},
  {id:'bascal',name:'Bascal Ofenheiss',place:'Castelo Ravenloft · cripta',role:'Chef',kind:'Histórico',
    summary:'Cozinheiro lembrado pelo epitáfio de sua cripta.'},
  {id:'eisglaze',name:'Barão Eisglaze Driif',place:'Castelo Ravenloft · cripta',role:'Barão falecido',kind:'Histórico',
    summary:'Barão sepultado nas criptas de Ravenloft.'},
  {id:'gralmore',name:'Gralmore Nimblenobs',place:'Castelo Ravenloft · cripta',role:'Mago',kind:'Histórico',
    summary:'“Mago Ordinário”, segundo a cripta. O botão de mármore de seu cajado abre um compartimento secreto sob a laje.'},
  {id:'kroval',name:'General Kroval Grislek',aliases:['Cachorro Louco'],place:'Castelo Ravenloft · cripta',role:'General · Mestre da Caça',kind:'Histórico',
    summary:'“Um líder de cães e homens”, chamado de Cachorro Louco e Mestre da Caça.'},
  {id:'tatsaul',name:'Tatsaul Eris',place:'Castelo Ravenloft · cripta',role:'Último da linhagem',kind:'Histórico',
    summary:'Lembrado em sua cripta como “o Último da Linhagem”.'},
  {id:'artank',name:'Artank Swilovich',place:'Castelo Ravenloft · cripta',role:'Destilador de vinho',kind:'Histórico',
    summary:'Amigo da família e membro da Guilda Baroviana dos Destiladores de Vinho, sepultado nas criptas.'},

  // ——— Van Richten
  {id:'vanrichten',name:'Rudolph van Richten',aliases:['Rictavio'],place:'Vallaki · Torre de Van Richten',role:'Caçador de vampiros',kind:'Aliado',
    summary:'Lendário caçador de monstros, escondido em Vallaki como Rictavio, um bardo meio-elfo de circo com uma carroça e um tigre-dentes-de-sabre.',
    detail:'Médico e estudioso de Darkon, perdeu o filho Erasmus, vendido por Vistani ao vampiro Barão Metus, e a esposa Ingrid, morta por vingança. Veio a Baróvia para matar Strahd e espera o momento certo, disfarçado por um chapéu mágico e com a mente protegida por um anel. Estuda os Guardiões da Pena e desconfia dos Vistani. Foi mentor de Ezmerelda, mas nunca confiou plenamente nela. Usa a antiga torre de Khazan como base.',
    tarokka:'Relutante, muda de ideia se o grupo mencionar a leitura das cartas.'},
  {id:'ezmerelda',name:'Ezmerelda d’Avenir',place:'Baróvia · itinerante',role:'Caçadora de monstros',kind:'Aliada',
    summary:'Vistana e antiga pupila de van Richten. Entra em Baróvia à procura do mentor e para enfrentar Strahd.',
    detail:'Ainda menina, viu a própria família raptar Erasmus e depois viu van Richten poupar seus pais. Aos quinze anos fugiu de casa, encontrou-o e caçou criaturas da noite com ele por dois anos; a falta de confiança dele acabou com a parceria. Tem uma perna de madeira, mantém uma carroça perto da torre de van Richten e pode ser encontrada na Abadia de Santa Markóvia e em outros locais.',
    tarokka:'Pode ser o aliado indicado pelas cartas; forjar uma aliança com ela é um marco da campanha.'},
  {id:'ingrid',name:'Ingrid',place:'Passado de van Richten',role:'Esposa de van Richten',kind:'Histórico',
    summary:'Amor de infância e esposa de Rudolph van Richten, mãe de Erasmus. Foi morta pelo Barão Metus como vingança.'},
  {id:'erasmus',name:'Erasmus',place:'Passado de van Richten',role:'Filho de Rudolph e Ingrid',kind:'Histórico',
    summary:'Raptado aos catorze anos por Vistani e vendido ao vampiro Barão Metus, que o transformou em cria. A pedido dele, o próprio pai o destruiu com uma estaca.'},
  {id:'metus',name:'Barão Metus',place:'Passado de van Richten',role:'Vampiro',kind:'Histórico',
    summary:'Vampiro que comprou Erasmus como servo e o transformou em cria. Matou Ingrid por vingança e foi destruído por van Richten.'},

  // ——— Ganchos de aventura
  {id:'duquesa',name:'Duquesa Morwen',place:'Vau da Adaga · gancho',role:'Governante de Vau da Adaga',kind:'Neutra',
    summary:'No gancho “Visitantes Misteriosos”, pede aos aventureiros que levem aos Vistani de Stanimir uma ordem para deixar suas terras.'},
  {id:'zelraun',name:'Zelraun Roaringhorn',place:'Vau da Adaga · gancho',role:'Agente dos Harpistas',kind:'Aliado',
    summary:'Harpista que veio a Vau da Adaga oferecer o apoio da organização à duquesa Morwen. No gancho “Lobisomens nas Brumas”, dá aos Harpistas pergaminhos de remover maldição e paga a prata para suas armas.'},
  {id:'eravien',name:'Eravien Haund',place:'Vau da Adaga · gancho',role:'Agente da Aliança dos Lordes',kind:'Aliado',
    summary:'Transmite aos membros da Aliança dos Lordes informações obtidas de um lobisomem capturado.'},
  {id:'lanniver',name:'Lanniver Strayl',place:'Vau da Adaga · gancho',role:'Cavaleiro da Ordem da Manopla',kind:'Aliado',
    summary:'Seguidor de Tyr que entrega poções aos membros da Ordem enviados contra os lobisomens.'},
  {id:'davra',name:'Davra Jassur',place:'Águas Profundas · gancho',role:'Agente Zhentarim',kind:'Neutra',
    summary:'Recrutadora da Rede Negra e assassina impiedosa. Quer a cabeça do líder da matilha que matou seu marido, Yarak, e deve um favor a quem a conseguir.'},
  {id:'yarak',name:'Yarak',place:'Águas Profundas · passado',role:'Agente Zhentarim',kind:'Histórico',
    summary:'Membro da Rede Negra, marido de Davra Jassur, morto por lobisomens ao escoltar uma caravana a caminho da Estalagem do Caminho.'}
];

const peopleById = Object.fromEntries(people.map(person => [person.id, person]));

// Relações em pares: [a, b, o que b é para a, o que a é para b].
// Cada rótulo descreve a pessoa ligada do ponto de vista da ficha aberta:
// na ficha de Strahd, Barov aparece como "pai"; na ficha de Barov, Strahd aparece como "filho".
const relations = [
  // Família von Zarovich e o ciclo de Tatyana
  ['strahd','barov','pai','filho primogênito'],
  ['strahd','ravenovia','mãe','filho primogênito'],
  ['strahd','sergei','irmão caçula, que ele matou','irmão mais velho e assassino'],
  ['strahd','eva','meia-irmã (ele não sabe)','meio-irmão'],
  ['strahd','tatyana','amor obsessivo do passado','pretendente que ela rejeitou'],
  ['strahd','marina','reencarnação que ele perseguiu','sedutor e algoz'],
  ['strahd','ireena','alvo de sua obsessão','perseguidor'],
  ['barov','ravenovia','esposa','marido'],
  ['barov','sergei','filho caçula','pai'],
  ['barov','eva','filha com uma mulher Vistana','pai'],
  ['ravenovia','sergei','filho caçula','mãe'],
  ['sergei','tatyana','noiva','noivo'],
  ['sergei','ireena','reencarnação de sua noiva','amado de sua vida passada'],
  ['tatyana','marina','reencarnação posterior','vida anterior'],
  ['tatyana','ireena','reencarnação atual','vida anterior'],
  ['marina','ireena','reencarnação posterior','vida anterior'],
  ['eva','arabelle','descendente','antepassada'],

  // Corte e servos de Ravenloft
  ['strahd','rahadin','mordomo e servo leal','senhor'],
  ['barov','rahadin','membro honorário da família','rei que o adotou'],
  ['strahd','escher','consorte','senhor e amante'],
  ['strahd','sasha','esposa vampírica','marido e senhor'],
  ['strahd','ludmilla','noiva vampírica','senhor'],
  ['strahd','anastrasya','noiva vampírica','senhor'],
  ['strahd','volenta','noiva vampírica','senhor'],
  ['strahd','helga','criada vampírica','senhor'],
  ['strahd','cyrus','cozinheiro do castelo','senhor'],
  ['strahd','lief','contador do castelo','senhor'],
  ['strahd','pidlwick','boneco que ele tolera','senhor que ele teme'],
  ['strahd','beucephalus','montaria','senhor'],
  ['strahd','gertruda','jovem que ele enfeitiçou','anfitrião que a enfeitiçou'],
  ['strahd','dorfniya','noiva que não conquistou seu amor','noivo'],
  ['strahd','khazan','arquimago que ergueu Ravenloft','senhor que o empregou'],
  ['strahd','baba','parteira que se diz sua mãe','“filho” que ela venera'],
  ['ravenovia','baba','parteira que ela baniu','rainha que a baniu'],
  ['barov','stefan_gregorovich','primeiro conselheiro','rei'],
  ['barov','ciril','sumo sacerdote estimado','rei'],
  ['ravenovia','ciril','sumo sacerdote estimado','rainha'],
  ['dorfniya','pidlwick_first','bobo da corte','senhora'],
  ['dorfniya','pidlwick','réplica que ela encomendou','senhora que o encomendou'],
  ['pidlwick_first','pidlwick','réplica que o matou','original que ele matou'],
  ['tatyana','pidlwick_first','bobo que a divertia','senhora a quem divertia'],
  ['sergei','pidlwick_first','bobo que o divertia','senhor a quem divertia'],
  ['sergei','khazan','arquimago que desmontou sua espada','dono da espada que ele desmontou'],

  // Inimigos e vítimas de Strahd
  ['strahd','vanrichten','caçador que ele quer capturar','alvo de sua caçada'],
  ['strahd','ezmerelda','caçadora que o enfrenta','alvo'],
  ['strahd','madmage','mago que o desafiou','inimigo que o derrotou'],
  ['strahd','doru','cria que ele criou','criador e senhor'],
  ['strahd','kasimir','elfo que ele puniu','algoz de seu povo'],
  ['strahd','patrina','pretendente élfica do passado','o poder que ela desejava'],
  ['strahd','argynvost','dragão que ele matou','seu matador'],
  ['strahd','vladimir','inimigo que o odeia','alvo de seu ódio'],
  ['strahd','godfrey','cavaleiro que ele matou','seu matador'],
  ['strahd','markovia','santa que o enfrentou','vampiro que ela desafiou'],
  ['strahd','lazlo','burgomestre que ele matou','seu matador'],
  ['strahd','grigor','sacerdote que ele matou','seu matador'],
  ['strahd','leo','traidor que ele caçou','senhor que traiu'],
  ['strahd','dalvan','mensageiro morto por seus lobos','senhor dos lobos que o mataram'],
  ['strahd','emil','prisioneiro','carcereiro'],

  // Agentes e cúmplices
  ['strahd','arrigal','agente Vistana','senhor verdadeiro'],
  ['strahd','luvash','líder Vistana a seu serviço','senhor'],
  ['strahd','kiril','líder da matilha a seu serviço','protetor e senhor'],
  ['strahd','fiona','simpatizante em Vallaki','conde que ela apoia'],
  ['strahd','henrik','cúmplice em Vallaki','patrono (como Vasili von Holtz)'],
  ['strahd','abbot','deva que ele corrompeu','corruptor (como Vasili von Holtz)'],
  ['strahd','vasilka','noiva que o Abade lhe destina','noivo pretendido'],

  // Vila de Baróvia
  ['ireena','ismark','irmão adotivo','irmã adotiva'],
  ['ireena','kolyan','pai adotivo','filha adotiva'],
  ['ireena','izek','irmão biológico (nenhum dos dois sabe)','irmã perdida (ele não sabe)'],
  ['ismark','kolyan','pai','filho'],
  ['ismark','strahd','conde que ele sonha enfrentar','irmão de Ireena, que quer enfrentá-lo'],
  ['kolyan','dalvan','mensageiro de sua carta','senhor'],
  ['kolyan','donavich','sacerdote que pode fazer seu funeral','burgomestre falecido'],
  ['kolyan','arrigal','impostor que usou seu nome','nome usado na carta falsa'],
  ['donavich','doru','filho, preso sob a igreja','pai'],
  ['madmage','doru','seguidor na revolta','líder da revolta'],
  ['mary','gertruda','filha','mãe'],
  ['mary','blinsky','fabricante de sua boneca','cliente de muitos anos'],
  ['bildrath','parriwimple','sobrinho','tio'],
  ['alenka','mirabel','sócia na taverna','sócia na taverna'],
  ['alenka','sorvia','sócia na taverna','sócia na taverna'],
  ['mirabel','sorvia','sócia na taverna','sócia na taverna'],
  ['arik','alenka','patroa','barman da taverna'],
  ['arik','mirabel','patroa','barman da taverna'],
  ['arik','sorvia','patroa','barman da taverna'],
  ['alenka','eva','vidente que ela recomenda','Vistana da taverna'],
  ['morgantha','bella','filha','mãe'],
  ['morgantha','offalia','filha','mãe'],
  ['bella','offalia','irmã','irmã'],
  ['morgantha','lucianjarov','criança que ela levou','bruxa que o levou'],

  // Casa da Morte
  ['gustav','elisabeth','esposa','marido'],
  ['gustav','rose','filha','pai'],
  ['gustav','thorn','filho','pai'],
  ['gustav','walter','filho com a ama','pai'],
  ['elisabeth','rose','filha','mãe'],
  ['elisabeth','thorn','filho','mãe'],
  ['elisabeth','walter','enteado','madrasta'],
  ['rose','thorn','irmão','irmã'],
  ['rose','walter','meio-irmão','meia-irmã'],
  ['thorn','walter','meio-irmão','meio-irmão'],

  // Vistani
  ['arrigal','luvash','irmão','irmão'],
  ['arrigal','arabelle','sobrinha','tio'],
  ['luvash','arabelle','filha','pai'],
  ['arabelle','bluto','sequestrador','vítima'],
  ['eva','stanimir','Vistana que leva viajantes até ela','líder de seu povo'],
  ['stanimir','duquesa','governante que ordena sua partida','líder Vistana a ser expulso'],

  // Elfos das sombras
  ['kasimir','patrina','irmã que ele ajudou a apedrejar','irmão que orquestrou seu apedrejamento'],
  ['rahadin','kasimir','elfo cujas orelhas ele cortou','algoz que cortou suas orelhas'],
  ['rahadin','patrina','rival que ele afastou de Strahd','inimigo na corte'],

  // Vallaki
  ['vargas','lydia','esposa','marido'],
  ['vargas','victor','filho','pai'],
  ['lydia','victor','filho','mãe'],
  ['vargas','izek','capanga e capitão da guarda','senhor'],
  ['vargas','fiona','rival','rival'],
  ['vargas','udo','prisioneiro','burgomestre que o prendeu'],
  ['vargas','lars','guarda que ele prendeu','burgomestre que o prendeu'],
  ['lydia','lucian','irmão mais velho','irmã mais nova'],
  ['lydia','tasha','antepassada','descendente'],
  ['lucian','tasha','antepassada','descendente'],
  ['lydia','abbot','Abade que deseja seu vestido de noiva','dona do vestido que ele quer'],
  ['victor','stella','moça que ele humilhou','rapaz que a humilhou'],
  ['izek','blinsky','fabricante de suas bonecas','cliente'],
  ['fiona','nikolaiold','marido falecido','esposa'],
  ['fiona','nikolai','filho','mãe'],
  ['fiona','karl','filho','mãe'],
  ['fiona','stella','filha','mãe'],
  ['fiona','ernst','espião e conselheiro','senhora'],
  ['fiona','izek','capanga que ela quer morto','inimiga do barão'],
  ['fiona','leo','traidor cujos ossos sua família guarda','guardiã de seus ossos'],
  ['nikolaiold','nikolai','filho','pai'],
  ['nikolaiold','karl','filho','pai'],
  ['nikolaiold','stella','filha','pai'],
  ['nikolai','karl','irmão','irmão'],
  ['nikolai','stella','irmã','irmão'],
  ['karl','stella','irmã','irmão'],
  ['lucian','stella','moça que ele pode acolher','padre que pode acolhê-la'],
  ['lucian','yeska','coroinha','padre'],
  ['lucian','milivoj','coveiro','padre'],
  ['lucian','willemina','fiel da igreja','padre'],
  ['lucian','andral','santo de sua igreja','guardião de seus ossos'],
  ['milivoj','yeska','coroinha que lhe contou o segredo','quem ouviu seu segredo'],
  ['milivoj','henrik','comprador dos ossos','vendedor dos ossos'],
  ['milivoj','andral','santo cujos ossos ele roubou','ladrão de seus ossos'],
  ['henrik','andral','santo cujos ossos ele esconde','quem esconde seus ossos'],
  ['udo','willemina','mãe','filho'],
  ['szoldar','yevgeni','parceiro de caça','parceiro de caça'],
  ['blinsky','piccolo','macaco','dono'],
  ['blinsky','vanrichten','quem lhe deu Piccolo (como Rictavio)','fabricante que ganhou Piccolo'],
  ['piccolo','vanrichten','antigo dono','macaco que ele deu'],
  ['gunther','yelena','esposa','marido'],
  ['gunther','vanrichten','dono da carroça que guarda','guarda sua carroça'],
  ['yelena','vanrichten','dono da carroça que guarda','guarda sua carroça'],
  ['nikolai','vanrichten','dono do tigre que ele soltou','rapaz que soltou seu tigre'],
  ['karl','vanrichten','dono do tigre que ele soltou','rapaz que soltou seu tigre'],

  // Martikov e Guardiões da Pena
  ['davian','urwin','filho do meio (afastado)','pai (afastado)'],
  ['davian','adrian','filho','pai'],
  ['davian','elvir','filho','pai'],
  ['davian','stefania','filha','pai'],
  ['urwin','adrian','irmão','irmão'],
  ['urwin','elvir','irmão','irmão'],
  ['urwin','stefania','irmã','irmão'],
  ['adrian','elvir','irmão','irmão'],
  ['adrian','stefania','irmã','irmão'],
  ['elvir','stefania','irmã','irmão'],
  ['urwin','danika','esposa','marido'],
  ['urwin','brom','filho','pai'],
  ['urwin','bray','filho','pai'],
  ['danika','brom','filho','mãe'],
  ['danika','bray','filho','mãe'],
  ['brom','bray','irmão','irmão'],
  ['davian','brom','neto','avô'],
  ['davian','bray','neto','avô'],
  ['stefania','dag','marido','esposa'],
  ['stefania','claudiu','filho','mãe'],
  ['stefania','martin','filho','mãe'],
  ['stefania','viggo','filho','mãe'],
  ['stefania','yolanda','filha','mãe'],
  ['dag','claudiu','filho','pai'],
  ['dag','martin','filho','pai'],
  ['dag','viggo','filho','pai'],
  ['dag','yolanda','filha','pai'],
  ['claudiu','martin','irmão','irmão'],
  ['claudiu','viggo','irmão','irmão'],
  ['claudiu','yolanda','irmã','irmão'],
  ['martin','viggo','irmão','irmão'],
  ['martin','yolanda','irmã','irmão'],
  ['viggo','yolanda','irmã','irmão'],
  ['davian','claudiu','neto','avô'],
  ['davian','martin','neto','avô'],
  ['davian','viggo','neto','avô'],
  ['davian','yolanda','neta','avô'],
  ['urwin','vanrichten','hóspede (como Rictavio)','estalajadeiro'],
  ['urwin','muriel','companheira dos Guardiões','companheiro dos Guardiões'],
  ['davian','muriel','amiga da família','amigo'],
  ['davian','baba','bruxa que tem uma de suas gemas','dono da gema que ela tem'],
  ['baba','muriel','espiã dos homens-corvo','bruxa que ela vigia'],

  // Krezk e a abadia
  ['dmitri','anna','esposa','marido'],
  ['dmitri','ilya','filho falecido','pai'],
  ['anna','ilya','filho falecido','mãe'],
  ['dmitri','abbot','Abade de quem desconfia','burgomestre de Krezk'],
  ['anna','abbot','Abade que ela louva','devota de Krezk'],
  ['abbot','vasilka','criação','criador'],
  ['abbot','clovin','servo de duas cabeças','senhor'],
  ['abbot','otto','porteiro e coveiro','senhor'],
  ['abbot','zygfrek','porteira e coveira','senhor'],
  ['abbot','mishka','pária que ele transformou','criador'],
  ['abbot','marzena','pária que ele transformou','criador'],
  ['abbot','markovia','santa cujo legado veio honrar','deva enviado em seu nome'],
  ['mishka','marzena','irmã mais velha','irmão mais novo'],
  ['clovin','marzena','pária a quem leva comida','único em quem ela confia'],
  ['clovin','otto','parente (família Belview)','parente (família Belview)'],
  ['clovin','zygfrek','parente (família Belview)','parente (família Belview)'],
  ['otto','zygfrek','parceira no portão','parceiro no portão'],
  ['clovin','cyrus','parente (família Belview)','parente (família Belview)'],

  // Argynvostholt
  ['argynvost','vladimir','comandante de campo','senhor da Ordem'],
  ['argynvost','godfrey','cavaleiro da Ordem','senhor da Ordem'],
  ['vladimir','godfrey','amado','amado'],
  ['vladimir','eva','vidente que o fez recuar','cavaleiro que ela deteve'],

  // Berez
  ['marina','lazlo','burgomestre que a matou para salvá-la','jovem que ele matou para salvar'],
  ['marina','grigor','sacerdote que a matou para salvá-la','jovem que ele matou para salvar'],
  ['lazlo','grigor','cúmplice','cúmplice'],

  // Lobisomens
  ['kiril','emil','rival que ele aprisionou','líder rival'],
  ['kiril','zuleika','inimiga','líder que ela quer morto'],
  ['kiril','bianca','companheira','companheiro'],
  ['kiril','skennis','membro da matilha','líder'],
  ['kiril','wensencia','membro da matilha','líder'],
  ['kiril','kellen','criança que ele infectou','líder que a infectou'],
  ['emil','zuleika','companheira','companheiro'],
  ['wensencia','kellen','aprendiz','treinadora'],
  ['kellen','blinsky','fabricante de sua boneca','fabricante do brinquedo'],
  ['davra','kiril','líder da matilha que ela quer morto','inimiga'],
  ['davra','yarak','marido falecido','esposa'],

  // Templo Âmbar
  ['exethanter','neferon','guardião do templo','lich do templo'],
  ['vilnius','jakarion','mestre falecido','aprendiz'],

  // Van Richten
  ['vanrichten','ezmerelda','antiga pupila','mentor'],
  ['vanrichten','ingrid','esposa falecida','marido'],
  ['vanrichten','erasmus','filho falecido','pai'],
  ['vanrichten','metus','vampiro que ele destruiu','caçador que o destruiu'],
  ['vanrichten','khazan','construtor da torre que ele ocupa','atual ocupante de sua torre'],
  ['ingrid','erasmus','filho','mãe'],
  ['metus','erasmus','servo que ele transformou','senhor e algoz'],
  ['metus','ingrid','vítima de sua vingança','assassino'],
  ['duquesa','zelraun','Harpista que lhe oferece apoio','governante a quem oferece apoio']
];

for (const person of people) person.links = [];
for (const [a, b, bForA, aForB] of relations) {
  if (!peopleById[a] || !peopleById[b]) throw new Error(`Relação inválida: ${a} ↔ ${b}`);
  if (peopleById[a].links.some(([id]) => id === b)) throw new Error(`Relação repetida: ${a} ↔ ${b}`);
  peopleById[a].links.push([b, bForA]);
  peopleById[b].links.push([a, aForB]);
}

// Escala editorial de relevância para consulta na mesa:
// 5 = campanha inteira; 4 = arco importante; 3 = capítulo ou decisão relevante;
// 2 = encontro/local; 1 = participação breve ou referência histórica.
const tierGroups = {
  5: 'strahd ireena tatyana vanrichten eva',
  4: 'ismark sergei rahadin baba ezmerelda kasimir vargas fiona izek urwin davian abbot argynvost vladimir godfrey',
  3: 'kolyan barov ravenovia patrina madmage arrigal luvash arabelle donavich doru morgantha bella offalia victor stella lucian milivoj henrik bluto blinsky danika adrian elvir stefania vasilka clovin dmitri anna marina lazlo kiril emil zuleika exethanter neferon escher pidlwick muriel rose thorn gustav elisabeth khazan',
  2: 'stanimir mary gertruda bildrath parriwimple alenka mirabel sorvia lydia nikolaiold nikolai karl ernst yeska udo willemina lars szoldar yevgeni brom bray dag otto zygfrek cyrus ilya markovia grigor bianca skennis kellen vilnius ludmilla anastrasya volenta walter gunther yelena mishka marzena wensencia helga tasha leo beucephalus lucianjarov sasha ingrid erasmus metus duquesa davra andral lorde_klutz pidlwick_first dorfniya'
};
for (const person of people) person.tier = 1;
for (const [tier, ids] of Object.entries(tierGroups)) {
  for (const id of ids.split(' ')) {
    if (!peopleById[id] || peopleById[id].tier !== 1) throw new Error(`Tier inválido ou repetido: ${id}`);
    peopleById[id].tier = Number(tier);
  }
}
